permissions:
 - "SFTRAINING-ACLASS-INDEX"
 - "SFTRAINING-ASSIGN-POINTS"
 - "SFTRAINING-ASSIGN-STUDENT-CLASS-INDEX"
 - "SFTRAINING-GRADE-ADJUSTMENT"
 - "SFTRAINING-TEACHERS"
 - "SFTRAINING-ATTENDANCE"
 - "SFTRAINING-DASHBOARD-SCORE-MANAGER"
 - "SFTRAINING-MMODULES-DETAILS"
 - "SFTRAINING-DASHBOARD-INDEX"
 - "REEVALUATIONS-DUYET"
 - "SFTRAINING-MANAGER-EXAM-LIST"
 - "SFTRAINING-MANAGER-EXAM-SCHEDULE"
 - "SFTRAINING-STUDENTS-INDEX"
 - "SFTRAINING-STUDENT-CLASS-INDEX"
 - "SFTRAINING-UPDATE-MPROGRAM-CLASS-FOR-STUDENT-INDEX"
 - "SFTRAINING-WARNING-STUDING-INDEX"
 - "SFTRAINING-REPORTS-INDEX"
 - "SFTRAINING-PAYMENT-MANAGER-INDEX"
 - "SFTRAINING-PAYMENTS-INDEX"
 - "SFTRAINING-TBFEES-INDEX"
 - "SFTRAINING-MPROGRAMS-INDEX"
 - "SFTRAINING-LEARNS-INDEX"
 - "SFTRAINING-LESSION-PLANS"
 - "SFTRAINING-TIMETABLES"
 - "SFTRAINING-LIST-STUDY"
 - "SFTRAINING-LEARNING-MANAGEMENT"
 - "SFTRAINING-MMODULES-INDEX-CLONE"
 - "SFTRAINING-MCLASSES-INDEX"
 - "SFTRAINING-RE-ENROLLS"
 - "SFTRAINING-ASSIGN-CONSULTANT-INDEX"
 - "SFTRAINING-EXAM-MANAGER"
 - "SFTRAINING-SCORE-MANAGER"
 - "SFTRAINING-SCORE-MANAGER-MMODULE"
 - "SFTRAINING-TRAINING-POINTS"
 - "SFTRAINING-REEVALUATIONS"
 - "SFTRAINING-MMODULES-INDEX"
 - "SFTRAINING-MMODULES-SETTINGS"
 - "SFTRAINING-STUDENTLEARNING-INDEX"
 - "SFTRAINING-ACADEMIC-REVIEW-INDEX"
 - "SFTRAINING-STANDRADIZED-REVIEW-INDEX"
 - "SFTRAINING-GRADUTEDSTUDENT-INDEX"
 - "SFTRAINING-HISACTIVITIES"
 - "DOCUMENTS-APP-SFT"
 - "SFTRAINING-DOCUMENTS-INDEX"
 - "SFTRAINING-LINK-ERP"
 - "SFTRAINING-LINK-CSVC"
 - "RELEASE-NOTES-BUTTON"
 - "SFTRAINING-ADD-CLASS-LESSION-PLANS"
 - "SFTRAINING-LESSION-PLANS-DELETE-ADMIN"
 - "SFTRAINING-LESSION-PLANS-BTN-PENDING"
 - "SFTRAINING-LESSION-PLANS-BTN-APPROVE"
 - "SFTRAINING-MMODULES-INDEX-CLONE-DELETE"
 - "SFTRAINING-NOTIFICATION-INDEX"
 - "REEVALUATIONS-PHAN-GV"
 - "REEVALUATIONS-CHAM-PHUC-KHAO"
 - "REEVALUATIONS-HO-SO-PHUC-KHAO"
 - "DELETE-RELEASE-NOTES"
 - "SFTRAINING-SCHEDULE-SAVE"
 - "SFTRAINING-CREATE-SCHEDULE"
 - "SFTRAINING-SCHEDULE-HANDLE-LEADER-APPROVE"
 - "USER-ASSIGN-LEADER-DEPARTMENT"
 - "SCHEDULE-SAVE-ERP-LEADER-HANDLE"
 - "SCHEDULE-SAVE-APPROVE-DEPARTMENT"
 - "SFTRAINING-SCORE-MANAGER-INDEX"
 - "SFTRAINING-SCORE-MANAGER-DETAILS-SCORE-WITH-CLASS"
 - "SFTRAINING-MMODULES-CHANGE-GRADE-SEMESTER"
 - "SFTRAINING-SCORE-MANAGER-DEL"
 - "SFTRAINING-STANDRADIZED-CREATE"
 - "SFTRAINING-STANDRADIZED-INDEX"
 - "SFTRAINING-STUDENTS-GRADUATE-SITUATION"
 - "SFTRAINING-SCORE-MANAGER-INPUT-SCORE"
 - "RELIGIONS"
 - "SFTRAINING-GRADING-ASSIGNMENT"
 - "SFTRAINING-MEXAMS-MANAGER"
 - "SCORE-MANAGER-INPUT-SCORE-MMODULE"
 - "SFTRAINING-SURVEY"
 - "SFTRAINING-CONFIRM-STU-INITCLASS"
 - "SFTRAINING-UPDATE-STUDENT-STATE-INDEX"
 - "SFTRAINING-MMODULES-INDEX-CLONE-ADD-STUDENT-TO-MMODULE"
 - "SFTRAINING-ACLASS-CHANGE-INDEX"
 - "SFTRAINING-NOTIFY-SCORE"
 - "SFTRAINING-LMS-CONFIGURATION"
 - "SFTRAINING-LMS-LEARNING-PROCESS"
 - "SFTRAINING-LMS-INDEX"
 - "SFTRAINING-MANAGEMENT-EXAM-PLAN"
 - "SFTRAINING-MANAGEMENT-EXAM-SUPERVISION"
 - "SFTRAINING-EXAM-PUBLISHING"
 - "SFTRAINING-DEV"
 - "SFTRAINING-MANAGEMENT-EXAM-PREPARATION"
 - "SFTRAINING-MMODULES-INDEX-CLONE-ROLL-UP"
 - "SFTRAINING-INDIVIDUAL-TITLE"
 - "SFTRAINING-BUSINESS-TITLE"
 - "SFTRAINING-STUDENTS-TITLE"
 - "SFTRAINING-ADMISSIONS-INDEX"
 - "SFTRAINING-ADVISES-INDEX"
 - "SFTRAINING-PAYMENT-MANAGER-TITLE"
 - "SFTRAINING-LIST-STUDY-TITLE"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX"
 - "SFTRAINING-EXAM-FORM-INDEX"
 - "SFTRAINING-SCORE-MANAGER-TITLE"
 - "SFTRAINING-SCORE-MANAGER-FREE-MMODULE"
 - "SFTRAINING-SCORE-MANAGER-PRINT-SCORE-WITH-CLASS"
 - "SFTRAINING-SCORE-MANAGER-PRINT-SCORE-WITH-STUDENT"
 - "SFTRAINING-REEVALUATIONS-TITLE"
 - "SFTRAINING-REEVALUATIONS-INDEX"
 - "SFTRAINING-REEVALUATIONS-GRADE-ADJUSTMENT-MANAGERS"
 - "SFTRAINING-MEXAMS-INDEX"
 - "SFTRAINING-MEXAMS-EXAM-RESULT-STATISTICS-INDEX"
 - "SFTRAINING-MEXAMS-EXAM-RESULT-STATISTICS-INDEX-HDKD"
 - "SFTRAINING-MEXAMS-QUESITEM-PERSONAL-INDEX"
 - "SFTRAINING-QR-CODE-INDEX"
 - "SFTRAINING-STUDENT-BREACHES-INDEX"
 - "SFTRAINING-ACADEMIC-REVIEW-TITLE"
 - "SFTRAINING-GRADUATION-MANAGER-TITLE"
 - "SFTRAINING-STANDRADIZED-COURSE-INDEX"
 - "SFTRAINING-GRADUATION-INDEX"
 - "SFTRAINING-GRADUATION-REVIEW-INDEX"
 - "SFTRAINING-GRADUATION-REPORT-INDEX"
 - "SFTRAINING-STUDENTLEARNING-TITLE"
 - "SFTRAINING-STUDENTS-INDEX-IMPORT-STUDENT"
 - "SFTRAINING-STUDENTS-INDEX-SEND-MAIL-STUDENT"
 - "SFTRAINING-STUDENTS-INDEX-SEND-MAIL-LECTURE"
 - "SFTRAINING-STUDENTS-INDEX-EXPORT-STUDENT"
 - "SCORE-MANAGER-APPROVE-SCORE-MMODULE"
 - "SFTRAINING-LIST-OF-STUDENTS-PARTICIPATING-IN-THE-EXAM"
 - "SFTRAINING-PAYMENTS-INDEX-LIST-STUDENTS"
 - "SFTRAINING-PAYMENTS-DETAILS-UPDATE"
 - "SFTRAINING-CHAPTER-INDEX"
 - "SFTRAINING-QUESTMP-REASSIGN"
 - "SFTRAINING-DELETE-TYPE-OF-POINT"
 - "SFTRAINING-ADD-STUDENT-TO-MCLASS"
 - "SFTRAINING-ACLASS-INDEX-LIST-STUDENT"
 - "SFTRAINING-ACLASS-INDEX-LIST-STUDENT-FREE-COURSES"
 - "SFTRAINING-UPDATE-MPROGRAM-CLASS-FOR-STUDENT-IMPORT"
 - "SFTRAINING-MMODULES-INDEX-CLONE-GROUP-STUDENTS"
 - "SFTRAINING-PAYMENTS-INDEX-DISCOUNT"
 - "SFTRAINING-PAYMENTS-INDEX-EXPORT-IMPORT"
 - "SFTRAINING-TBFEES-INDEX-EXPORT-IMPORT"
 - "SFTRAINING-TBFEES-INDEX-FOR-STUDENT"
 - "SFTRAINING-LESSION-PLANS-DEL-ADM"
 - "SFTRAINING-LESSION-PLANS-ADD-STUDENT"
 - "SFTRAINING-LESSION-PLANS-PRINT"
 - "SFTRAINING-LESSION-PLANS-EXCEL"
 - "SFTRAINING-LESSION-PLANS-EXPORT-PDF"
 - "SFTRAINING-LESSION-PLANS-VIEW-SCHEDULE"
 - "SFTRAINING-CREATE-SCHEDULE-IMPORT-EXCEL"
 - "SFTRAINING-CREATE-SCHEDULE-EXPORT-EXCEL"
 - "SFTRAINING-LEARNING-MANAGEMENT-LIST-MMODULES"
 - "SFTRAINING-MMODULES-INDEX-EXPORT-EXCEL"
 - "SFTRAINING-MMODULES-INDEX-PRINT"
 - "SFTRAINING-MMODULES-INDEX-LGRADE"
 - "SFTRAINING-MMODULES-INDEX-CHAPTERS"
 - "SFTRAINING-MMODULES-INDEX-CHAPTER"
 - "SFTRAINING-MMODULES-INDEX-DETAILS"
 - "SFTRAINING-MMODULES-INDEX-DETAILS-EXPORT-EXCEL"
 - "SFTRAINING-MMODULES-INDEX-DETAILS-IMPORT-EXCEL"
 - "SFTRAINING-ACADEMIC-REVIEW-INDEX-LIST-STUDENT-NOT-GRADE"
 - "SFTRAINING-ACADEMIC-REVIEW-INDEX-EXPORT-EXCEL"
 - "SFTRAINING-STUDENTLEARNING-INDEX-PRINT"
 - "SFTRAINING-STUDENTLEARNING-INDEX-EXPORT-EXCEL"
 - "SFTRAINING-SURVEY-CREATE-QUESTIONS"
 - "SFTRAINING-TRAINING-POINTS-IMPORT-EXCEL"
 - "SFTRAINING-MCLASSES-INDEX-RE-CLASS"
 - "SFTRAINING-MCLASSES-INDEX-ADD-STUDENT"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX-LGRADE"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX-ADD-STUDENT-TO-MMODULE"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX-DETAILS"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX-DETAILS-EXPORT-EXCEL"
 - "SFTRAINING-MMODULES-RE-CLASS-INDEX-DETAILS-IMPORT-EXCEL"
 - "SFTRAINING-MMODULES-INDEX-CLONE-LGRADE"
 - "SFTRAINING-MMODULES-INDEX-CLONE-COPY-LGRADE"
 - "SFTRAINING-MMODULES-INDEX-CLONE-SET-GROUPS"
 - "SFTRAINING-MMODULES-INDEX-CLONE-ASSIGN-TEACHER"
 - "SFTRAINING-MANAGER-LIST-STUDENT-EXAM"
 - "SFTRAINING-SCORE-PERMISSIONS"
 - "SCORE-MANAGER-INPUT-SCORE-MMODULE-PKT"
 - "SFTRAINING-PAYMENTS-DETAILS-DTEXTENSION"
 - "SFTRAINING-MMODULES-RE-CLASS-SET-GROUPS"
 - "SFTRAINING-MMODULES-RE-CLASS-GROUP-STUDENTS"
 - "SFTRAINING-ENROLLMENT-TITLE"
 - "SFTRAINING-ADMISSIONS-INDEX"
 - "SFTRAINING-ADVISES-INDEX"
 - "SFTRAINING-ADMISSIONS-UPDATE"
 - "SFTRAINING-ADMISSIONS-DEL"
 - "SFTRAINING-ADDITIONAL-EXAM-INFO"
 - "SFTRAINING-ATTENDANCE-MANAGEMENT"
 - "SFTRAINING-ROLLBACK-SCHEDULE"
 - "SFTRAINING-ASSIGN-SCHEDULE"
 - "SFTRAINING-MMODULES-RE-CLASS-ROLL-UPS"
 - "SFTRAINING-EXAM-QUESTION-SET"
 - "SFTRAINING-EXAM-QUESTION-SET-TEACHER"
 - "SFTRAINING-ATTEND-TEACHER"
 - "SFTRAINING-TBFEES-INDEX-LIST-STUDENT"
 - "SFTRAINING-RETAKE-APPROVE"
 - "SFTRAINING-RETAKE-INDEX"
 - "SFTRAINING-RETAKE-LIST"
 - "SFTRAINING-MANAGER-OLD-MEXAM"
 - "SFTRAINING-LIBADMISSIONMETHOD-INDEX"
 - "SFTRAINING-ADMISSIONRESULT-INDEX"
 - "SFTRAINING-RETAKE-REGISTER-IMPROVE-MMODULE"
 - "SFTRAINING-RETAKE-DEL-STUDENT"
 - "SFTRAINING-ADMISSION-RESULT-UPDATE"
 - "SFTRAINING-ADMISSION-RESULT-DEL"
 - "SFTRAINING-LIBADMISSIONMETHOD-UPDATE"
 - "SFTRAINING-LIBADMISSIONMETHOD-DEL"
 - "SFTRAINING-MMODULES-MPROGRAM-INDEX"
 - "SFTRAINING-MMODULES-MPROGRAM-INDEX-CHAPTER"
 - "SFTRAINING-MMODULES-MPROGRAM-INDEX-DETAILS"
 - "SFTRAINING-MMODULES-MPROGRAM-INDEX-DETAILS-IMPORT-EXCEL"
 - "SFTRAINING-MMODULES-MPROGRAM-INDEX-DETAILS-EXPORT-EXCEL"
 - "SFTRAINING-RETAKE-DETAILS-LIST"
 - "SFTRAINING-EXAM-SWITCHING"
 - "SFTRAINING-SCHEDULE-RESQUEST-UPDATE"
 - "SFTRAINING-MEXAMS-EXPORT-DOCX"
 - "SFTRAINING-MEXAMS-CLONE"
 - "SFTRAINING-ADMISSIONS-RESULT-DEL"
 - "SFTRAINING-REPORT-PLO-CLO"
 - "SFTRAINING-MEXAM-CHECKING"
 - "SFTRAINING-EXAM-SCORE-DOWNLOAD"
 - "SFTRAINING-EXAM-SCORE-UPLOAD"
 - "SFTRAINING-LMS-INDEX"
 - "SFTRAINING-LMS-DASHBOARD"
 - "SFTRAINING-LMS-CONTENT-REVIEW"
 - "SFTRAINING-LMS-TBM-APPROVED"
 - "SFTRAINING-LMS-CONFIGURATION"
 - "SCORE-MANAGER-CLOSING-SCORE-MMODULE"
 - "SFTRAINING-MCLASSES-INDEX-REFRESH-STUDENT"
 - "SFTRAINING-LMS"
 - "SFTRAINING-LMS-GV-SUBMIT"
 - "SFTRAINING-CHAPTERS-GV-ASSIGN"
 - "SFTRAINING-LMS-TRAINING-PLAN"
 - "SFTRAINING-LMS-LIBRARY"
 - "SFTRAINING-LMS-TBM-VIEW"
 - "SFTRAINING-MMODULES-INDEX-CHAPTERS-ADD"
 - "SFTRAINING-LOOKUP-MANAGER"
 - "SFTRAINING-FREE-MMODULE-INDEX"
 - "SFTRAINING-FREE-MMODULE-DETAILS"
 - "SFTRAINING-MMODULES-RE-CLASS-UPDATE-LIST-STUDENT"
 - "SFTRAINING-MMODULES-INDEX-CLONE-UPDATE-LIST-STUDENT"
 - "SFTRAINING-LMS-PERSONAL-LEARN"
 - "SFTRAINING-LMS-PERSONAL-COURSES"
 - "SFTRAINING-DEGREE-MANAGEMENT-TITLE"
 - "SFTRAINING-DEGREE-IMPORT-TITLE"
 - "SFTRAINING-DEGREE-STORE-MANAGEMENT"
 - "SFTRAINING-DEGREES-INDEX"
 - "SFTRAINING-FM"
 - "SFTRAINING-ADMINISTRATION"
 - "SFTRAINING-SCORE-MANAGER-CHANGE"
 - "SFTRAINING-SCORE-MANAGER-CHANGE-BGH"
 - "TEAM-DEV-DEBUG"
 - "SFTRAINING-MMODULES-DEL-STU-IN-MMODULE"
 - "SFTRAINING-EXPORT-GRADE"
 - "SFTRAINING-MEXAMS-ENGLISH-CLONE"
 - "SFTRAINING-MEXAMS-INDEX-ENGLISH"
 - "SFTRAINING-MEXAMS-ENGLISH-DETAIL"
 - "SFTRAINING-TBM-THNN-DUYET"
 - "RECEIVE-NOTICE-BEFORE-EXAM"
 - "RECEIVE-NOTICE-BIG-SIZE-FILE-BEFORE-EXAM"
 - "SFTRAINING-RE-CLASSES-INDEX"
 - "SFTRAINING-MEXAMS-ENGLISH-RUBRIC-LIBRARY"
 - "SFTRAINING-MEXAMS-ENGLISH-RUBRIC-LIBRARY-CONFIG"
 - "SFTRAINING-MEXAMS-ENGLISH-RUBRIC-LIBRARY-APPROVE"
