permissions:
- "HTTPS-ERP-BMTU-EDU-VN-MASSET-LANG-VI"
- "MASSET-BROWSE-SCHEDULE"
- "MASSET-RECEIVE-SCHEDULES"
- "MASSET-REGISTER-TO-USE-INDEX"
- "MASSET-REGISTER-TO-USE-PROCESS-INDEX"
- "MASSET"
- "MASSET-CAMPUS-INDEX"
- "MASSET-ASSET-INDEX"
- "MASSET-VEHICLES-INDEX"
- "MASSET-TOOLS-INDEX"
- "MASSET-DIGITAL-TOOLS-INDEX"
- "MASSET-PROVIDERS-INDEX"
- "MASSET-SETTINGS"
- "MASSET-PROCESS"
- "MASSET-REGISTER-TO-USE-HISTORY-INDEX"
- "MASSET-REGISTER-TO-USE-REPORT-INDEX"
- "MASSET-REGISTER-TO-USE-HISTORY-USE-INDEX"
- "MASSET-IS-APPROVAL"
- "MASSET-CONSUMABLES-INDEX"
- "MASSET-LIQUIDATION-MANAGEMENT"
- "MASSET-LIQUIDATION-HANDLE"
- "MASSET-LIQUIDATION-REPORT"
- "MASSET-LIQUIDATION-APPROVE"
- "MASSET-LIQUIDATION-CONFIRM"
- "MASSET-LIQUIDATION-CREATE"
- "MASSET-LIQUIDATION-DELETE"
- "MASSET-LIQUIDATION-DETAILS"
- "MASSET-LIQUIDATION-EDIT"
- "MASSET-LIQUIDATION-PROGRESS"
- "MASSET-LIQUIDATION-REQUEST"
- "MASSET-SETTLEMENT-CONFIRM"
- "MASSET-SHOPPING-MANAGEMENT"
- "MASSET-MAINTENANCE-MANAGEMENT"
- "MASSET-ORDERS-PROCESS-INDEX"
- "MASSET-ORDERS-HISTORY-INDEX"
- "MASSET-ORDER-REPORT-INDEX"
- "MASSET-REPAIR-MANAGEMENT"
- "MASSET-IMPORT-INSTANCE"
- "MASSET-REPORT-MALFUNCTIONS-REPORT-INDEX"
- "MASSET-REPORT-MALFUNCTIONS-FOLLOW-REQUEST"
- "MASSET-REPORT-MALFUNCTIONS-INDEX"
- "MASSET-PURCHASE-COMPANY-INDEX"
- "MASSET-ROOMS-INDEX"
- "MASSET-BUILDINGS-INDEX"
- "MASSET-DUNG-CU-CONG-CU"
- "MASSET-MAY-MOC-THIET-BI"
- "MASSET-NOI-THAT"
- "MASSET-VAT-TU-TIEU-HAO"
- "MASSET-DEPRECIATION-MANAGEMENT"
- "MASSET-IMPORT-FILE"
- "MASSET-ASSETS"
- "MASSET-CONG-CU-SO"
- "MASSET-CONG-CU-DUNG-CU"
- "MASSET-THIET-BI-CNTT"
- "MASSET-ADD-GROUP"
- "MASSET-EDIT-GROUP"
- "MASSET-DEL-GROUP"
- "MASSET-DEL-TAG"
- "MASSET-DEL-ROOMTYPELIB"
- "MASSET-DEL-MANUFACTURE"
- "MASSET-DEL-ALLASSET"
- "MASSET-DEL-PROVIDER"
- "MASSET-DEL-CAMPUS"
- "MASSET-DEL-BUILDING"
- "MASSET-EXPORT-CAMPUS"
- "MASSET-DEL-ROOM"
- "MASSET-AMAINTANCE-ROOM"
- "MASSET-DEL-INSTANCE"
- "MASSET-COPY-INSTANCE"
- "MASSET-TRANSFER-INSTANCE"
- "MASSET-ADD-TAG"
- "MASSET-ADD-ROOMTYPELIB"
- "MASSET-ADD-ALLASSET"
- "MASSET-ADD-CAMPUS"
- "MASSET-ADD-BUILDING"
- "MASSET-ADD-ROOM"
- "MASSET-ADD-INSTANCE"
- "MASSET-EDIT-TAG"
- "MASSET-EDIT-ROOMTYPELIB"
- "MASSET-EDIT-MANUFACTURE"
- "MASSET-EDIT-ALLASSET"
- "MASSET-EDIT-CAMPUS"
- "MASSET-EDIT-BUILDING"
- "MASSET-EDIT-ROOM"
- "MASSET-EDIT-INSTANCE"
- "MASSET-ADD-HOLIDAY"
- "MASSET-EDIT-HOLIDAY"
- "MASSET-DEL-HOLIDAY"
- "MASSET-ASSET-ALL-ASSET"
- "MASSET-MANUFACTURERS-INDEX"
- "MASSET-ROOMTYPELIBS-INDEX"
- "MASSET-TAGS-INDEX"
- "MASSET-GROUPS-INDEX"
- "MASSET-HOLIDAYS-INDEX"
- "MASSET-ADD-PROVIDER"
- "MASSET-EDIT-PROVIDER"
- "MASSET-COPY-PROVIDER"
- "MASSET-PROCESS-INDEX-DETAIL"
- "MASSET-PROCESS-INDEX-PROCESS-TABLE"
- "ADMIN-ERP"
- "MASSET-PROCESS-INDEX-REJECT"
- "MASSET-ORDER-ADMIN-INDEX"
- "MASSET-UPDATE-PAYMENT"
- "MASSET-DEV"
- "MASSET-GENERATE-INSTANCE"
- "SFTRAINING"
- "MASSET-ADD-MANUFACTURE"
- "MASSET-HISACTIVITIVES-INDEX"
- "MASSET-QR-ROOM"
- "MASSET-SHOW-ASSETS"
- "MASSET-CHANGE-USER-HANDLE"
- "MASSET-QR-CODE-INDEX"
- "MASSET-EXPORT-INSTANCE"
- "MASSET_NOTIFICATIONS"
- "MASSET-READ-ORDER"
- "MASSET-EXIMS-IMPORT-WAREHOUSE"
- "MASSET-EXIMS-EXPORT-WAREHOUSE"
- "MASSET-EXIMS-INVENTORY-SUMMARY"
- "MASSET-EXIMS-OPERATION-HISTORY"
- "MASSET-MANAGER-WAREHOUSES"
- "MASSET-EXIMS-WAREHOUSE-MANAGEMENT"
- "MASSET-EXIMS-IMPORT"
- "MASSET-EXIMS-EXPORT"
- "MASSET-EXIMS"
- "MASSET-WAREHOUSE-MANAGEMENT"